animal = "  Chanchito feliz  "
print(animal.upper())
print(animal.lower())
print(animal.capitalize())
print(animal.title())
print(animal.strip())
print(animal.strip().capitalize())
print(animal.lstrip())
print(animal.rstrip())
print(animal.find("Ch"))
print(animal.find("CH"))
print(animal.replace("nch", "j"))
print("nch" in animal)
print("nch" not in animal)
