mascotas = ["Wolfgang", "Pelusa", "Pulga", "Copito"]
print(mascotas)
print(mascotas[0])
print(mascotas[1])
print(mascotas[2])
print(mascotas[3])
mascotas[0] = "Bicho"
print(mascotas[0])
print(mascotas)
print(mascotas[0:3])
print(mascotas[1:3])
print(mascotas[:3])
print(mascotas[2:])
print(mascotas[-1:])
print(mascotas[::2])
print(mascotas[1::2])
# print(mascotas[1:2:2])

numeros = list(range(21))
print(numeros)
print(numeros[::2])
print(numeros[1::2])
print(numeros[::2])

numeros2 = list(range(1, 21))
print(numeros2[1::2])
print(numeros2[::2])
